# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-yocto:
    runs-on: [self-hosted, linux, x64, yocto]
    steps:

    - name: update meta-dmg
      run:  |
        cd /home/bhupiister/engicam_bsp_release/sources/meta-dmg
        git pull origin main
        git status
        
    - name: Build Yocto Rootfs
      run:  |
        cd /home/bhupiister/engicam_bsp_release
        source setup-environment build
        bitbake dmg-matisse-r5-imx8p
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: images
        path: /home/bhupiister/engicam_bsp_release/build/tmp/deploy/images/imx8mp-icore/dmg-matisse-r5-imx8p-imx8mp-icore.wic.zst
        retention-days: 1
        
        
